import type { Ctx } from './context.js';
/**
 * Protocol-major negotiation — the one place the CLI decides which wire it speaks.
 *
 * `spec/v2/core/versioning.md` §1.5: a client selects the highest major it
 * implements that the host advertises in `protocolVersions[]`. This CLI
 * implements 2 and 1. Every command keeps its `/v1/<op>` literal; at the
 * request boundary (`resolveRequest`) two rewrites apply under major 2 only:
 *
 *  1. A literal whose unversioned twin is an operation named in
 *     `spec/v2/path-manifest.json` is rewritten to that twin with
 *     `OpenWOP-Version: 2.0` (§1.2 — the `/v1/` keys are the same operations
 *     through the overlap; §1.3 — the header selects major 2 on an unversioned
 *     name).
 *  2. A host-proprietary `/v1/host/<org>/…` literal (e.g. the reference host's
 *     `/v1/host/openwop-app/*`) is rewritten to the unversioned root the host
 *     advertises for that org under `extensions.*` (`{ root: "/host/<org>/",
 *     twin: "/v1/host/<org>/" }`, versioning.md §5), WITHOUT a version header —
 *     a `/host/<org>/…` path has no major and is outside §1.4. When no root is
 *     advertised the `/v1` twin is sent unchanged (it MAY ride the overlap).
 *
 * Anything else passes through exactly as written.
 *
 * Negotiation happens once per process: `/.well-known/openwop` is read ONCE
 * with `OpenWOP-Version: 2` so a dual-stack host answers with its v2
 * representation — the only one that carries the §5 `extensions.<org>.host`
 * mount (the header-less default is `preferredVersion`, i.e. the v1 document,
 * which does not). A host that does not serve major 2 answers `406` with
 * `details.protocolVersions` (§1.3), which is read the same way; a host that
 * ignores the header returns its only document. Both representations carry
 * `protocolVersions`. The major and the root map are memoized on
 * `ctx.protocolMajor` / `ctx.hostRoots`. `OPENWOP_PROTOCOL_MAJOR=1|2` pins the
 * major without a probe — the escape hatch for a host whose discovery lies;
 * under a pin no root is known, so `/v1/host/<org>/…` is sent unchanged.
 */

/** Majors this CLI implements, highest first (§1.5 precedence). */
export const CLI_PROTOCOL_MAJORS = [2, 1] as const;
export type ProtocolMajor = (typeof CLI_PROTOCOL_MAJORS)[number];

/**
 * Operation + channel path templates from `spec/v2/path-manifest.json`.
 * `/.well-known/openwop` and `/openapi.json` are omitted (`V2_MANIFEST_OMITTED`):
 * they carry no `/v1/` prefix and are addressed by the same name under both
 * majors. GENERATED by `node scripts/sync-path-manifest.mjs <openwop-corpus>` —
 * do not hand-edit between the markers; `test/path-manifest.test.mjs` fails if
 * this list drifts from `test/fixtures/v2-path-manifest-paths.json`.
 */
// BEGIN GENERATED V2_PATH_TEMPLATES (corpus v2.42.6-15-g61b66240, path-manifest.json @ 95312706; 45 paths, 43 embedded)
export const V2_PATH_TEMPLATES: readonly string[] = [
  '/agents',
  '/agents/org-chart',
  '/agents/org-chart/{departmentId}',
  '/agents/roster',
  '/agents/roster/{rosterId}',
  '/agents/{agentId}',
  '/agents/{agentId}/deployments',
  '/audit/verify',
  '/content/pages',
  '/content/pages/{pageId}/sections/{sectionId}',
  '/content/pages/{slug}',
  '/content/settings',
  '/host/effect-seams',
  '/host/events',
  '/interrupts/{token}',
  '/prompts',
  '/prompts/{templateId}',
  '/prompts:render',
  '/runs',
  '/runs/{runId}',
  '/runs/{runId}/ancestry',
  '/runs/{runId}/annotations',
  '/runs/{runId}/artifacts/{artifactId}',
  '/runs/{runId}/cancel',
  '/runs/{runId}/compensation',
  '/runs/{runId}/effects',
  '/runs/{runId}/eval-summary',
  '/runs/{runId}/events',
  '/runs/{runId}/events/poll',
  '/runs/{runId}/interrupts/{nodeId}',
  '/runs/{runId}:diff',
  '/runs/{runId}:fork',
  '/runs/{runId}:pause',
  '/runs/{runId}:resume',
  '/runs:bulk-cancel',
  '/tools',
  '/tools/{toolId}',
  '/trigger-subscriptions',
  '/webhooks',
  '/webhooks/{webhookId}',
  '/webhooks/{webhookId}/dead-letters',
  '/webhooks/{webhookId}/rotate-secret',
  '/workflows/{workflowId}',
];
// END GENERATED V2_PATH_TEMPLATES

/** Manifest paths deliberately not embedded (no `/v1/` twin to rewrite). */
export const V2_MANIFEST_OMITTED: readonly string[] = ['/.well-known/openwop', '/openapi.json'];

const V2_MATCHERS: readonly RegExp[] = V2_PATH_TEMPLATES.map(
  (t) => new RegExp(`^${t.replace(/[.:]/g, '\\$&').replace(/\{[A-Za-z]+\}/g, '[^/]+')}$`),
);

/**
 * The unversioned twin of a `/v1/<op>` path when `<op>` is a manifest-named
 * operation, else null. A query string is carried over untouched.
 */
export function v2Twin(path: string): string | null {
  const q = path.indexOf('?');
  const bare = q === -1 ? path : path.slice(0, q);
  const query = q === -1 ? '' : path.slice(q);
  if (!bare.startsWith('/v1/')) return null;
  const unversioned = bare.slice('/v1'.length);
  return V2_MATCHERS.some((m) => m.test(unversioned)) ? `${unversioned}${query}` : null;
}

/** Highest major the CLI implements among those the host advertises; 1 when the host says nothing usable. */
export function selectMajor(protocolVersions: unknown): ProtocolMajor {
  const advertised = Array.isArray(protocolVersions) ? protocolVersions.filter((v): v is string => typeof v === 'string') : [];
  for (const major of CLI_PROTOCOL_MAJORS) {
    if (advertised.some((v) => v.startsWith(`${major}.`))) return major;
  }
  return 1;
}

/**
 * Host-proprietary roots advertised in discovery `extensions` (versioning.md §5),
 * as `{ "/v1/host/<org>/": "/host/<org>/" }`. An entry needs a `root` under
 * `/host/<org>/`; its `twin` (when present) must be `/v1/host/<org>/…` and is
 * the prefix it replaces, else the twin is derived by prefixing `/v1`.
 */
export function hostRootsFrom(extensions: unknown): Record<string, string> {
  const roots: Record<string, string> = {};
  if (!extensions || typeof extensions !== 'object' || Array.isArray(extensions)) return roots;
  const withSlash = (s: string) => (s.endsWith('/') ? s : `${s}/`);
  for (const value of Object.values(extensions as Record<string, unknown>)) {
    if (!value || typeof value !== 'object') continue;
    const { root, twin } = value as { root?: unknown; twin?: unknown };
    if (typeof root !== 'string' || !/^\/host\/[^/]+(\/|$)/.test(root)) continue;
    const r = withSlash(root);
    const t = typeof twin === 'string' ? withSlash(twin) : `/v1${r}`;
    if (!/^\/v1\/host\/[^/]+\//.test(t)) continue;
    roots[t] = r;
  }
  return roots;
}

/** The advertised unversioned root for a `/v1/host/<org>/…` path, else null. */
export function hostRootFor(path: string, roots: Readonly<Record<string, string>>): string | null {
  if (!path.startsWith('/v1/host/')) return null;
  let best: string | null = null;
  for (const twin of Object.keys(roots)) {
    if (path.startsWith(twin) && (best === null || twin.length > best.length)) best = twin;
  }
  return best === null ? null : `${roots[best]}${path.slice(best.length)}`;
}

/**
 * Read `/.well-known/openwop` once and memoize the selected major (and, under
 * major 2, the advertised host-proprietary roots) on ctx.
 */
export async function negotiateMajor(ctx: Ctx): Promise<ProtocolMajor> {
  if (ctx.protocolMajor !== undefined) return ctx.protocolMajor;
  const pinned = ctx.env?.OPENWOP_PROTOCOL_MAJOR;
  if (pinned === '1' || pinned === '2') {
    ctx.protocolMajor = Number(pinned) as ProtocolMajor;
    ctx.hostRoots = {};
    return ctx.protocolMajor;
  }
  let major: ProtocolMajor = 1;
  let roots: Record<string, string> = {};
  try {
    const url = new URL('.well-known/openwop', ctx.baseUrl.endsWith('/') ? ctx.baseUrl : `${ctx.baseUrl}/`);
    const res = await ctx.fetchImpl(url, { method: 'GET', headers: { accept: 'application/json', 'openwop-version': '2' } });
    const doc = JSON.parse(await res.text()) as {
      protocolVersions?: unknown;
      extensions?: unknown;
      details?: { protocolVersions?: unknown };
    } | null;
    if (res.ok) {
      major = selectMajor(doc?.protocolVersions);
      if (major === 2) roots = hostRootsFrom(doc?.extensions);
    } else if (res.status === 406) {
      // §1.3: the host does not serve major 2 and echoes what it does serve.
      major = selectMajor(doc?.details?.protocolVersions);
    }
  } catch {
    // Unreachable or non-JSON discovery: stay on the v1 default (§1.3). The
    // command's own request reports the failure with its usual message.
  }
  ctx.protocolMajor = major;
  ctx.hostRoots = roots;
  return major;
}

/**
 * Rewrite a request for the negotiated major. Under major 2 a manifest-named
 * `/v1/<op>` becomes `/<op>` + `OpenWOP-Version: 2.0`, and a `/v1/host/<org>/…`
 * route becomes the host's advertised `/host/<org>/…` root (no version header).
 * Everything else — major 1, an already-unversioned path, a proprietary route
 * with no advertised root — passes through unchanged.
 */
export async function resolveRequest(
  ctx: Ctx,
  path: string,
  headers: Record<string, string>,
): Promise<{ path: string; headers: Record<string, string> }> {
  const major = await negotiateMajor(ctx);
  if (major !== 2) return { path, headers };
  const twin = v2Twin(path);
  if (twin !== null) return { path: twin, headers: { ...headers, 'openwop-version': '2.0' } };
  const rooted = hostRootFor(path, ctx.hostRoots ?? {});
  if (rooted !== null) return { path: rooted, headers };
  return { path, headers };
}
