import type { Ctx } from './context.js';
import { CliError } from './errors.js';
import { projectRunIdsInPath } from './ids.js';
/**
 * Protocol-major negotiation — the one place the CLI decides which wire it speaks.
 *
 * `spec/v2/core/versioning.md` §1.5: a client selects the highest major it
 * implements that the host advertises in `protocolVersions[]`. This CLI
 * implements 2 and 1. Every command keeps its `/v1/<op>` literal; at the
 * request boundary (`resolveRequest`) three rewrites apply under major 2 only:
 *
 *  1. A literal whose unversioned twin is an operation named in
 *     `spec/v2/path-manifest.json` is rewritten to that twin with
 *     `OpenWOP-Version: 2.0` (§1.2 — the `/v1/` keys are the same operations
 *     through the overlap; §1.3 — the header selects major 2 on an unversioned
 *     name).
 *  2. A v1 seam literal with a seams-v2 operation (`V2_SEAM_PREFIXES`, e.g.
 *     `/v1/host/workspace/files`) is rewritten to its `/conformance/seams/…`
 *     twin with `OpenWOP-Version: 2.0` — only when the host advertises
 *     `conformance.seamsProfile: "openwop-conformance-seams-v2"`.
 *  3. A host-proprietary `/v1/host/<org>/…` literal (e.g. the reference host's
 *     `/v1/host/openwop-app/*`) is rewritten to the unversioned root the host
 *     advertises for that org under `extensions.*` (`{ root: "/host/<org>/",
 *     twin: "/v1/host/<org>/" }`, versioning.md §5), WITHOUT a version header —
 *     a `/host/<org>/…` path has no major and is outside §1.4. When no root is
 *     advertised the `/v1` twin is sent unchanged (it MAY ride the overlap).
 *
 * Anything else passes through exactly as written.
 *
 * Negotiation happens once per process: `/.well-known/openwop` is read ONCE
 * with `OpenWOP-Version: 2` so a dual-stack host answers with its v2
 * representation — the only one that carries the §5 `extensions.<org>.host`
 * mount (the header-less default is `preferredVersion`, i.e. the v1 document,
 * which does not). A host that does not serve major 2 answers `406` with
 * `details.protocolVersions` (§1.3), which is read the same way; a host that
 * ignores the header returns its only document. Both representations carry
 * `protocolVersions`. The major and the root map are memoized on
 * `ctx.protocolMajor` / `ctx.hostRoots`. `OPENWOP_PROTOCOL_MAJOR=1|2` pins the
 * major without a probe — the escape hatch for a host whose discovery lies;
 * under a pin no root is known, so `/v1/host/<org>/…` is sent unchanged.
 */

/** Majors this CLI implements, highest first (§1.5 precedence). */
export const CLI_PROTOCOL_MAJORS = [2, 1] as const;
export type ProtocolMajor = (typeof CLI_PROTOCOL_MAJORS)[number];

/**
 * Operation + channel path templates from `spec/v2/path-manifest.json`.
 * `/.well-known/openwop` and `/openapi.json` are omitted (`V2_MANIFEST_OMITTED`):
 * they carry no `/v1/` prefix and are addressed by the same name under both
 * majors. GENERATED by `node scripts/sync-path-manifest.mjs <openwop-corpus>` —
 * do not hand-edit between the markers; `test/path-manifest.test.mjs` fails if
 * this list drifts from `test/fixtures/v2-path-manifest-paths.json`.
 */
// BEGIN GENERATED V2_PATH_TEMPLATES (corpus v2.42.6-15-g61b66240, path-manifest.json @ 95312706; 45 paths, 43 embedded)
export const V2_PATH_TEMPLATES: readonly string[] = [
  '/agents',
  '/agents/org-chart',
  '/agents/org-chart/{departmentId}',
  '/agents/roster',
  '/agents/roster/{rosterId}',
  '/agents/{agentId}',
  '/agents/{agentId}/deployments',
  '/audit/verify',
  '/content/pages',
  '/content/pages/{pageId}/sections/{sectionId}',
  '/content/pages/{slug}',
  '/content/settings',
  '/host/effect-seams',
  '/host/events',
  '/interrupts/{token}',
  '/prompts',
  '/prompts/{templateId}',
  '/prompts:render',
  '/runs',
  '/runs/{runId}',
  '/runs/{runId}/ancestry',
  '/runs/{runId}/annotations',
  '/runs/{runId}/artifacts/{artifactId}',
  '/runs/{runId}/cancel',
  '/runs/{runId}/compensation',
  '/runs/{runId}/effects',
  '/runs/{runId}/eval-summary',
  '/runs/{runId}/events',
  '/runs/{runId}/events/poll',
  '/runs/{runId}/interrupts/{nodeId}',
  '/runs/{runId}:diff',
  '/runs/{runId}:fork',
  '/runs/{runId}:pause',
  '/runs/{runId}:resume',
  '/runs:bulk-cancel',
  '/tools',
  '/tools/{toolId}',
  '/trigger-subscriptions',
  '/webhooks',
  '/webhooks/{webhookId}',
  '/webhooks/{webhookId}/dead-letters',
  '/webhooks/{webhookId}/rotate-secret',
  '/workflows/{workflowId}',
];
// END GENERATED V2_PATH_TEMPLATES

/** Manifest paths deliberately not embedded (no `/v1/` twin to rewrite). */
export const V2_MANIFEST_OMITTED: readonly string[] = ['/.well-known/openwop', '/openapi.json'];

/**
 * v1 literals whose v2 operation has a different name. `/openapi.json` is in
 * the manifest (getOpenApiSpec) but has no `/v1/` twin to strip: the v1 CLI
 * reads the v1 key `/v1/openapi.json`, and a v2 host answers that key only at
 * major 1 (a `/v1/` key is a v1 operation, versioning.md §1.2).
 */
export const V2_RENAMED: Readonly<Record<string, string>> = { '/v1/openapi.json': '/openapi.json' };

/**
 * v1 host-sample literals whose v2 home is the conformance seams profile
 * (`api/seams-v2.yaml`, conformance.md §"The seams profile"): prefix → prefix.
 * Rewritten only under major 2 AND when the host advertises
 * `conformance.seamsProfile: "openwop-conformance-seams-v2"` — seams are a
 * testing surface outside the canonical API, so no advertisement, no rewrite.
 * A v1 seam with no seams-v2 operation (e.g. `/v1/host/sample/ui-plugin/rpc`)
 * is deliberately absent and passes through unchanged.
 */
export const V2_SEAMS_PROFILE = 'openwop-conformance-seams-v2';
export const V2_SEAM_PREFIXES: Readonly<Record<string, string>> = {
  '/v1/host/workspace/files': '/conformance/seams/workspace/files',
};

/** The seams-v2 twin of a v1 seam literal, else null. */
export function v2SeamTwin(path: string): string | null {
  for (const [v1, v2] of Object.entries(V2_SEAM_PREFIXES)) {
    if (path === v1 || path.startsWith(`${v1}/`) || path.startsWith(`${v1}?`)) return `${v2}${path.slice(v1.length)}`;
  }
  return null;
}

const V2_MATCHERS: readonly RegExp[] = V2_PATH_TEMPLATES.map(
  (t) => new RegExp(`^${t.replace(/[.:]/g, '\\$&').replace(/\{[A-Za-z]+\}/g, '[^/]+')}$`),
);

/**
 * The unversioned twin of a `/v1/<op>` path when `<op>` is a manifest-named
 * operation, else null. A query string is carried over untouched.
 */
export function v2Twin(path: string): string | null {
  const q = path.indexOf('?');
  const bare = q === -1 ? path : path.slice(0, q);
  const query = q === -1 ? '' : path.slice(q);
  if (!bare.startsWith('/v1/')) return null;
  if (V2_RENAMED[bare] !== undefined) return `${V2_RENAMED[bare]}${query}`;
  const unversioned = bare.slice('/v1'.length);
  return V2_MATCHERS.some((m) => m.test(unversioned)) ? `${unversioned}${query}` : null;
}

/** Highest major the CLI implements among those the host advertises; 1 when the host says nothing usable. */
export function selectMajor(protocolVersions: unknown): ProtocolMajor {
  const advertised = Array.isArray(protocolVersions) ? protocolVersions.filter((v): v is string => typeof v === 'string') : [];
  for (const major of CLI_PROTOCOL_MAJORS) {
    if (advertised.some((v) => v.startsWith(`${major}.`))) return major;
  }
  return 1;
}

/**
 * Host-proprietary roots advertised in discovery `extensions` (versioning.md §5),
 * as `{ "/v1/host/<org>/": "/host/<org>/" }`. An entry needs a `root` under
 * `/host/<org>/`; its `twin` (when present) must be `/v1/host/<org>/…` and is
 * the prefix it replaces, else the twin is derived by prefixing `/v1`.
 */
export function hostRootsFrom(extensions: unknown): Record<string, string> {
  const roots: Record<string, string> = {};
  if (!extensions || typeof extensions !== 'object' || Array.isArray(extensions)) return roots;
  const withSlash = (s: string) => (s.endsWith('/') ? s : `${s}/`);
  for (const value of Object.values(extensions as Record<string, unknown>)) {
    if (!value || typeof value !== 'object') continue;
    const { root, twin } = value as { root?: unknown; twin?: unknown };
    if (typeof root !== 'string' || !/^\/host\/[^/]+(\/|$)/.test(root)) continue;
    const r = withSlash(root);
    const t = typeof twin === 'string' ? withSlash(twin) : `/v1${r}`;
    if (!/^\/v1\/host\/[^/]+\//.test(t)) continue;
    roots[t] = r;
  }
  return roots;
}

/** The advertised unversioned root for a `/v1/host/<org>/…` path, else null. */
export function hostRootFor(path: string, roots: Readonly<Record<string, string>>): string | null {
  if (!path.startsWith('/v1/host/')) return null;
  let best: string | null = null;
  for (const twin of Object.keys(roots)) {
    if (path.startsWith(twin) && (best === null || twin.length > best.length)) best = twin;
  }
  return best === null ? null : `${roots[best]}${path.slice(best.length)}`;
}

/**
 * Does a discovery document advertise the host-extension surface at `v1Prefix`
 * (`/v1/host/<org>/<surface>`)? A major-1 document lists it in its `paths` map. A
 * major-2 document has no `paths` map; it advertises the host's extension ROOT in
 * `extensions` (versioning.md §5), which makes every route under that root
 * reachable, and the route itself answers 404 for a surface it does not mount.
 * Reading only `paths` refused every host-extension group against a v2-only host.
 */
export function hostSurfaceAdvertised(discovery: unknown, v1Prefix: string): boolean {
  if (!discovery || typeof discovery !== 'object') return false;
  const { paths, extensions } = discovery as { paths?: unknown; extensions?: unknown };
  if (paths !== null && typeof paths === 'object') {
    return Object.keys(paths as Record<string, unknown>).some((p) => p.startsWith(v1Prefix));
  }
  return hostRootFor(v1Prefix, hostRootsFrom(extensions)) !== null;
}

/**
 * Read `/.well-known/openwop` once and memoize the selected major (and, under
 * major 2, the advertised host-proprietary roots) on ctx.
 */
export async function negotiateMajor(ctx: Ctx): Promise<ProtocolMajor> {
  if (ctx.protocolMajor !== undefined) return ctx.protocolMajor;
  const pinned = ctx.env?.OPENWOP_PROTOCOL_MAJOR;
  if (pinned === '1' || pinned === '2') {
    ctx.protocolMajor = Number(pinned) as ProtocolMajor;
    ctx.hostRoots = {};
    return ctx.protocolMajor;
  }
  let major: ProtocolMajor = 1;
  let roots: Record<string, string> = {};
  let seams = false;
  try {
    const url = new URL('.well-known/openwop', ctx.baseUrl.endsWith('/') ? ctx.baseUrl : `${ctx.baseUrl}/`);
    const res = await ctx.fetchImpl(url, { method: 'GET', headers: { accept: 'application/json', 'openwop-version': '2' } });
    const doc = JSON.parse(await res.text()) as {
      protocolVersions?: unknown;
      extensions?: unknown;
      details?: { protocolVersions?: unknown };
    } | null;
    if (res.ok) {
      // Kept for the readers that render discovery (capabilities, doctor) so
      // they reuse this one fetch instead of issuing a second.
      ctx.discovery = { doc, servedVersion: res.headers?.get?.('openwop-version') ?? undefined };
      ctx.discoveredStreamBase = streamBaseFrom(doc?.extensions, ctx.baseUrl);
      major = selectMajor(doc?.protocolVersions);
      if (major === 2) {
        roots = hostRootsFrom(doc?.extensions);
        seams = (doc as { conformance?: { seamsProfile?: unknown } } | null)?.conformance?.seamsProfile === V2_SEAMS_PROFILE;
      }
    } else if (res.status === 406) {
      // §1.3: the host does not serve major 2 and echoes what it does serve.
      major = selectMajor(doc?.details?.protocolVersions);
    }
  } catch {
    // Unreachable or non-JSON discovery: stay on the v1 default (§1.3). The
    // command's own request reports the failure with its usual message.
  }
  ctx.protocolMajor = major;
  ctx.hostRoots = roots;
  ctx.seamsV2 = seams;
  return major;
}

/**
 * Rewrite a request for the negotiated major. Under major 2 a manifest-named
 * `/v1/<op>` becomes `/<op>` + `OpenWOP-Version: 2.0`, and a `/v1/host/<org>/…`
 * route becomes the host's advertised `/host/<org>/…` root (no version header).
 * Everything else — major 1, an already-unversioned path, a proprietary route
 * with no advertised root — passes through unchanged.
 */
export async function resolveRequest(
  ctx: Ctx,
  path: string,
  headers: Record<string, string>,
): Promise<{ path: string; headers: Record<string, string> }> {
  const major = await negotiateMajor(ctx);
  if (major !== 2) return { path, headers };
  const twin = v2Twin(path);
  // Tenant-bound `{runId}` params travel projected (`~2F`, not `%2F`) — src/ids.ts.
  if (twin !== null) return { path: projectRunIdsInPath(twin), headers: { ...headers, 'openwop-version': '2.0' } };
  const seam = ctx.seamsV2 ? v2SeamTwin(path) : null;
  if (seam !== null) return { path: seam, headers: { ...headers, 'openwop-version': '2.0' } };
  const rooted = hostRootFor(path, ctx.hostRoots ?? {});
  if (rooted !== null) return { path: rooted, headers };
  return { path, headers };
}

/** True for a loopback host (the local-development exception to the https rule). */
function isLoopback(url: URL): boolean {
  return url.hostname === 'localhost' || url.hostname === '127.0.0.1' || url.hostname === '[::1]' || url.hostname === '::1';
}

/**
 * A stream origin the USER chose (`--stream-base-url` / OPENWOP_STREAM_BASE_URL /
 * config `host.streamBaseUrl`): any scheme is honoured — it is the user's
 * decision — but it must parse and must not embed credentials; a trailing slash
 * is dropped. An unparseable value is a
 * usage error, not a silent fallback.
 */
export function explicitStreamBase(raw: unknown): string | undefined {
  if (typeof raw !== 'string' || raw.trim() === '') return undefined;
  let url: URL;
  try { url = new URL(raw.trim()); } catch { throw new CliError(`--stream-base-url / OPENWOP_STREAM_BASE_URL is not a URL: ${raw}`); }
  // Golden rule 3 (secrets are references, never values): a `user:pass@` URL
  // would sit in plaintext in ~/.openwop config and shell history. The bearer
  // already travels in the Authorization header.
  if (url.username !== '' || url.password !== '') {
    throw new CliError('--stream-base-url / OPENWOP_STREAM_BASE_URL must not carry credentials (user:pass@); pass them with --api-key.');
  }
  return raw.trim().replace(/\/+$/, '');
}

/**
 * The stream origin a HOST advertised (`extensions.<org>.<name>.streamBase`,
 * versioning.md §5 — host-proprietary; the reference host's
 * `openwop-app.host.streamBase`, openwop-app ADR 0761). The bearer is sent to
 * it, so it is accepted only when it cannot downgrade the connection or leave
 * the machine: from an `https:` base, an `https:` origin; from a loopback base,
 * only a loopback origin (local development). Never credentials, a query or a
 * fragment. Anything else → undefined (streams stay on the base URL).
 */
export function streamBaseFrom(extensions: unknown, baseUrl: string): string | undefined {
  if (!extensions || typeof extensions !== 'object' || Array.isArray(extensions)) return undefined;
  let base: URL;
  try { base = new URL(baseUrl); } catch { return undefined; }
  for (const value of Object.values(extensions as Record<string, unknown>)) {
    const raw = value && typeof value === 'object' ? (value as { streamBase?: unknown }).streamBase : undefined;
    if (typeof raw !== 'string') continue;
    let url: URL;
    try { url = new URL(raw); } catch { continue; }
    if (url.username !== '' || url.password !== '' || url.search !== '' || url.hash !== '') continue;
    // A loopback base is a local host: its streams stay local. (Off-machine
    // would also carry the CLI's automatic localhost development key, chosen
    // BECAUSE the base is local, to a host the user never named.)
    if (isLoopback(base)) { if (!isLoopback(url)) continue; }
    else if (url.protocol !== 'https:' || base.protocol !== 'https:') continue;
    return raw.replace(/\/+$/, '');
  }
  return undefined;
}

/**
 * THE one place an event-stream request is built (run events, host-extension
 * streams, board watch, present). Same path negotiation as `resolveRequest`,
 * joined to the STREAM origin — the user's `streamBaseUrl`, else the host's
 * accepted `streamBase`, else `baseUrl` — keeping any path prefix, with the
 * bearer attached. Non-stream requests never use this (they stay on `baseUrl`).
 *
 * Why a separate origin exists at all (openwop-app ADR 0761, MEASURED): a CDN
 * rewrite in front of a host may buffer a streamed response entirely —
 * `https://app.openwop.dev/api` delivered zero bytes of an event stream in 25 s.
 */
export async function resolveStreamRequest(
  ctx: Ctx,
  requestedPath: string,
  headers: Record<string, string>,
): Promise<{ url: URL; headers: Record<string, string> }> {
  const resolved = await resolveRequest(ctx, requestedPath, { accept: 'text/event-stream', ...headers });
  const { origin, source } = streamOrigin(ctx);
  // The bearer goes wherever the stream goes, so a move off --base-url is never silent under --verbose.
  if (ctx.verbose && source !== 'base') ctx.io.stderr.write(`openwop: reading the event stream from ${origin} (${STREAM_SOURCE_LABEL[source]})\n`);
  const url = new URL(resolved.path.replace(/^\//, ''), origin.endsWith('/') ? origin : `${origin}/`);
  const out = { ...resolved.headers };
  if (ctx.apiKey) out.authorization = `Bearer ${ctx.apiKey}`;
  return { url, headers: out };
}

export type StreamOriginSource = 'setting' | 'advertised' | 'base';

/** How each source is named to the user (doctor + --verbose). */
export const STREAM_SOURCE_LABEL: Readonly<Record<StreamOriginSource, string>> = {
  setting: 'your --stream-base-url / OPENWOP_STREAM_BASE_URL / config setting',
  advertised: "the host's advertised streamBase",
  base: '--base-url',
};

/**
 * Where event streams are read from, and why: the user's setting, else the
 * host's accepted `streamBase` (valid after `negotiateMajor` has run), else the
 * base URL. The one answer both `resolveStreamRequest` and `doctor` use. To keep
 * streams on `--base-url` (e.g. an egress proxy), set `--stream-base-url` to
 * the same value — a user setting always wins.
 */
export function streamOrigin(ctx: Ctx): { origin: string; source: StreamOriginSource } {
  if (ctx.streamBaseUrl) return { origin: ctx.streamBaseUrl, source: 'setting' };
  if (ctx.discoveredStreamBase) return { origin: ctx.discoveredStreamBase, source: 'advertised' };
  return { origin: ctx.baseUrl, source: 'base' };
}
